name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Decode SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh_private_key
        shell: bash

      - name: Set SSH permissions
        run: chmod 600 /tmp/ssh_private_key
        shell: bash

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          ssh -i /tmp/ssh_private_key -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
            # Clone the repository
            cd /path/to/your/deployment/directory
            git clone https://github.com/hng12-devbotops/fastapi-book-project.git
            cd fastapi-book-project

            # Create a virtual environment
            python3 -m venv venv
            source venv/bin/activate  # On Windows: venv\Scripts\activate

            # Install dependencies
            pip install -r requirements.txt

            # Start the server
            nohup uvicorn main:app --host 0.0.0.0 --port 80 &
          EOF
